spring:
  graphql:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
dgs:
  graphql:
    graphiql:
      enabled: true
      path: /dev/graphiql